spring:
  application:
      name: zuulgateway-service
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 30000
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
server:
  port: 8762
 
zuul:
  host:
    connect-timeout-millis: 6000000
    socket-timeout-millis: 6000000
  ignoredServices: '*' 
  routes:
    countries-service:
      path: /countryservices/**
      serviceId: countries-service
      stripPrefix: true
    user-service:
      path: /userservices/**
      serviceId: user-service
      stripPrefix: true
