spring:
  application:
      name: user-service  
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
server:
  port: 8001
